### ISSUE TITLE
Issue with converting array of arrays...

### ISSUE THREAD

**Issue by jfuehner** [KotoJallow/IonToJson#2]
Hi! I was trying to use your utility to convert a GeoJson ion object back to JSON. However, I ran into an issue where ionToJSON doesn't work with coordinate arrays of arrays (i.e., polygons).

Take a look at the console output in mounted.js from this [example](https://codesandbox.io/s/angry-raman-p2g49). Specifically, if you drill down into the feature collection/features/coordinates you will see the array of arrays is not converted back to JSON correctly... Thoughts?

Thanks!

**Comment by KotoJallow** [comment]
Hi @jfuehner ,
Thank you for writing.
Every thing seems to be okay. I ran your mounted.js and accessed data in arrays of arrays.
Have a look https://paste.ubuntu.com/p/sjNjwf7fPC/
Let me know if this helps
Thanks

**Comment by jfuehner** [comment]
Hiya! I took a look at your example and it too is not producing the correct results. Take a look at the external file being fetched...

[https://raw.githubusercontent.com/uber-common/deck.gl-data/master/examples/geojson/vancouver-blocks.json](https://raw.githubusercontent.com/uber-common/deck.gl-data/master/examples/geojson/vancouver-blocks.json)

That file contains a series of objects that look like...

`{"type":"Feature","geometry":{"type":"Polygon","coordinates":[[[-123.0249569,49.2407190],[-123.0241582,49.2407165],[-123.0240445,49.2406847],[-123.0239311,49.2407159],[-123.0238530,49.2407157],[-123.0238536,49.2404548],[-123.0249568,49.2404582],[-123.0249569,49.2407190]]]},"properties":{"valuePerSqm":4563,"growth":0.3592}}`

Specifically, the `coordinates` property which contains the nested arrays is where the issue lays...

`"coordinates":[[[-123.0249569,49.2407190],[-123.0241582,49.2407165],[-123.0240445,49.2406847],[-123.0239311,49.2407159],[-123.0238530,49.2407157],[-123.0238536,49.2404548],[-123.0249568,49.2404582],[-123.0249569,49.2407190]]]`

The ionToJson script is not regenerating the full original `coordinates` property. When I run ionToJson it produces a `coordinates` property that looks like the below...

`"coordinates":[[[-123.02495689999999,49.240719]]],"null":[-123.02495689999999,49.240719]`

See what I mean?

**Comment by KotoJallow** [comment]
@jfuehner thank you for raising this issue. It has been resolve in @2.0.1

**Comment by KotoJallow** [comment]
Issue resolved
